<?php
use Zend\Mvc\Controller\Plugin\FlashMessenger as PluginFlashMessenger;

/* 
 * Copyright (C) 2015 schurix
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

?>

<h1><?php echo $this->translate('E-Mail Configuration'); ?></h1>

<?php 
	$messengerClasses = array(
        PluginFlashMessenger::NAMESPACE_INFO => 'info',
        PluginFlashMessenger::NAMESPACE_ERROR => 'danger',
        PluginFlashMessenger::NAMESPACE_SUCCESS => 'success',
        PluginFlashMessenger::NAMESPACE_DEFAULT => 'info',
        PluginFlashMessenger::NAMESPACE_WARNING => 'warning'
	);
	$this->flashMessenger()->setMessageOpenFormat('<div%s>');
	$this->flashMessenger()->setMessageCloseString('</div>');
	$this->flashMessenger()->setMessageSeparatorString('</div><div%s>');
	foreach($messengerClasses as $messengerClass => $cssClass){
		echo $this->flashMessenger()->render($messengerClass, array('alert', 'alert-'.$cssClass, 'alert-dismissible'));
	}
?>

<?php 
echo $this->twbForm($this->emailForm);